# Site settings
title: Uncontended
name: Tim Brooks
email: tim@uncontended.net
description: > # this means to ignore newlines until "baseurl:"
  I'm Tim Brooks: A software engineer, replacement level data scientist,
  baseball fan, and hiking enthusiast.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tbrooks8.github.com" # the base hostname & protocol for your site
twitter_username: trb8
github_username:  tbrooks8
encoding: utf-8

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
gems:
  - jekyll-gist